# Generated by Django 4.1.2 on 2022-10-14 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('category_slug', models.SlugField(blank=True, max_length=128, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network_name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('social_network_link', models.CharField(max_length=1024, unique=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('excerpt', models.CharField(max_length=255, verbose_name='Excerpt')),
                ('keywords', models.CharField(max_length=255, verbose_name='Key words')),
                ('slug', models.SlugField(blank=True, max_length=128, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, upload_to='post_img/%Y/%m/%d', verbose_name='Image')),
                ('image_description', models.TextField(blank=True, verbose_name='Image description')),
                ('content', models.TextField(verbose_name='Content')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_content.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
